### PR TITLE
bridges | added pause menu to new bridge level

### LINKED ISSUE #174: bridges | embed pause menu from overworld into bridge level
## Motivation
You should be able to access the pause menu from everywhere in the game.

## Implementation
**It is important that the main menu which was already implemented in the overworld is the same menu that is accessed through the bridges. You should not simply copy-paste everything, but refer to the same scene.**

You can find the already implemented pause menu here:
```
Arch-enemies/overworld/ui/menu/menu
```

The menu consists of the script `pause_menu.gd` and the scene with the same name. 

- when you are in the bridge level, you should be able to press `ESC` and the pause menu appears 
-> to see how this was done in the overworld, check out how they did it and just do the same thing

**UPDATE**
In the last high-court meeting it was decided to embed the pause menu directly into the current scene, and not open a new one. It should contain all the old options, and make it a lot easier to implement a return button to the current active scene.
This could be done similarly to the goal menu, but should be generic enough to be able to be reused in the overworld without changes.

### PR DESCRIPTION
**Pull request by aylinfi**
## Motivation
closes #174 

The pause_menu wasn't accessible in the new bridge level, so it needed to be added.

## What was changed/added
The pause_menu isn't accessed by changing the scene like before, but by having a pause_menu node inside of the scene.
Opening it by pressing "esc" just changes the visibility of the node, so it can be opened and closed.

## Testing

https://github.com/mango-gremlin/arch-enemies/assets/116217918/7ab09900-117f-4232-b3f7-9ba650c068e3

You can open and close the pause_menu by pressing "esc". 
Interestingly enough it looks different when it actually changes the scene like in the overworld eventhough it's the same menu.

## Additional Information
You can still move the animals when the pause_menu is pressed. This is also the case in the goal_menu, so if we want to change this, both should be edited.

Both of the menus should also be updated in ther visual apperance by the UI team. Trying to center the menus is kind of frustrating since the bridge scene doesn't seem to actually fill the screen outline of godot, so the automatic centering options of godot also don't work.

### CODE REVIEW

**Review by Kabooni — APPROVED** [review]
It works, thank you!
I personally would prefer if the player couldn't move while some kind of menu is active. If you want, you can implement it because it's a small change, but if you don't want to, the UI team can do it later while finishing the menus appearance-wise.

**Review by Raining-Cloud — COMMENTED** [review]
https://github.com/mango-gremlin/arch-enemies/assets/59502349/84d64426-1374-4e50-a380-d14ef18babc3

**Comment by Kabooni** [comment]
@Raining-Cloud I'm not quite sure what you mean. The fox can't jump over the deer, that's not a bug, or is it something else?

**Comment by Kabooni** [comment]
> Well, shouldnt a pause menu actually pause the game ? Right now its just a ui component being displayed 😅
Ah yes, I agree with you. I've already written a comment on that topic, but I can understand why @aylinfi did it, as the goal menu has the same functionality.

**Comment by mango-gremlin** [comment]
I would say pausing the game (eg fox not moving etc) is not a priority but if @Kabooni  has time she can implement it when the pause menu ui is being implemented.
So should we merge this then?

**Pull request merged**
