### PR TITLE
overworld | ysort adjusted

### LINKED ISSUE #367: overworld | adjust ysort origins for less clipping issues
## Motivation
There were some issues with the clipping and when the fox was in front of things and when behind.

## Implementation
Go through sprites and adjust ysort origins so the clipping issues are less pronounced.

### PR DESCRIPTION
**Pull request by mango-gremlin**
## Motivation
closes #367 

There were clipping issues with some details in the overworld.

## What was changed/added
- collision adjusted for deer house
- collision adjusted for vertical bridge indicator floor
- collision adjusted for spider house
- collision adjusted for fox house

## Testing
deer house
image

fox house
image

spooder house
image

that one bush that needs to have less collision (otherwise no walking) - added collision on the side
image

Also changed the ysort on the vertical bridge floor thing for the last bridge. Will now be below the fox at all times.

### CODE REVIEW

**Review by ScatteredDrifter — APPROVED** [review]
I cannot test it locally due to personal circumstances, however with the images provided it seems to satisfy and resolve the described issues.

**Review by Kabooni — CHANGES_REQUESTED** [review]
It's quite easy to get under the bridges
grafik
grafik

And I've noticed that the antler are now behind the bed
grafik

**Comment by mango-gremlin** [comment]
> The collision adjustments are great and are working, but besides that, I've found some things that should be adjusted if there's time: It's quite easy to get under the bridges
> 
> And I've noticed that the antlers are now behind the bed 

antlers were behind the bed the whole time, but i can see if i can fix it.
about the bridges, i'll adjust that too, one min

**Review by Kabooni — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
