### PR TITLE
bridges | Changed conditional colors / animal backgrounds

### LINKED ISSUE #311: bridges | different colors for different conditional tiles
## Motivation
As per playtests, this would make the different zones easier to understand.

## Implementation
simply change the corresponding line in the make_visible function, but reference tileset with different colours. Colours should correspond to the corresponding animal maybe? Would require changing animal assets too, but this should be easy.

Proposed Colors:
ALLOWED = Green (Snake)
SIDE = Yellow (Squirrel)
BOTTOM = Pink? (Spider)
SHALLOW = Turquoise (Deer)

### PR DESCRIPTION
**Pull request by marcel-iv**
## Motivation
closes #311

## What was changed/added
Changed the colours of the shallows and bottom dropzones. Also changed animal backgrounds to reflect their corresponding dropzone

## Testing
This is how everything look like with the different colours. Code changes were minimal, and can all be seen with this picture, so I didn't bother with a video. 
Conditional_Zones_New_Color

## Additional Information
if you want a different color, please tell me the exact hexcode of said color.

### CODE REVIEW

**Review by mango-gremlin — CHANGES_REQUESTED** [review]
Thank you first of all, very nice.

I think I would have done the colours differently though
- thought we only said to change the colours of the zones, not the animals?
- in that same vein: i would have left squirrel at purple, and it's zone at yellow, i think that was never a problem? since yellow is for squirrel AND spider, its fine if its not the same colour. 
- spider zone: maybe to make it more clear that it's for the spider, make it purple? Maybe a purple very similar to the original spider background? the dark grey-yellow makes it look like its greyed out -> makes it harder to understand you're supposed to place something here
- deer green was very nice, the colour now I think is too dark and looks almost black depending on the screen - i would leave the deer green, or maybe change the deer to a mint? and then make the deer shallow zones also a light mint green.
- why was snake changed at all? i think it was the one thing we did not want to change, I would keep the yellow, the green looks just like the dropzone green, which is *really* confusing, and I dont see the reason for this change
- same with the spider, why was it changed at all?

To conclude: I would only change the colour of the deer, not the colour of any of the other animals.
& the for the zones I would only change the colour of shallows (minty green blue, or turquoise) and below animals (purple, for spider)

Colour Suggestions:
colours

For deer background: 
new_deer
hex code: 00e6b9

Deer Zone: hex code: 56e3d8

Spider Zone: hex code: 8d81c2

**Comment by marcel-iv** [comment]
> To conclude: I would only change the colour of the deer, not the colour of any of the other animals. (suggestion below) & the for the zones I would only change the colour of shallows (minty green blue, or turquoise) and below animals (purple, for spider) And for the rest, eg. squirrel sprite, snake sprite, spider sprite: revert to the old ones, maybe?

I was under the impression we wanted to change the animal background to match their respective tile, as this is what we discussed on discord. 

Anyways, I've changed it, now it looks like this.
image

I'm personally not a huge fan that the deer background is a slightly different colour than the shallows, and the purple is bit muted, but it should be enough to communicate the purpose.

**Comment by Raffael-Rack** [comment]
Anstelle des 2-farben approaches könnte man auch den tieren eine outline geben die ihre komplette collisionbox anzeigt. Würde das gut aussehen?

**Comment by Kabooni** [comment]
The new purple looks fine in my opinion, but the deer colours might get overlooked because it's so similar to the water colour.

> Anstelle des 2-farben approaches könnte man auch den tieren eine outline geben die ihre komplette collisionbox anzeigt. Würde das gut aussehen?

Might be a better way, but honestly, I would need to see an example to really form an opinion.

**Comment by mango-gremlin** [comment]
> Anstelle des 2-farben approaches könnte man auch den tieren eine outline geben die ihre komplette collisionbox anzeigt. Würde das gut aussehen?

I am also not sure what you mean, but honestly, I would not change things significantly at this point, as there is no way to playtest them - i would try to change things only minimally. There isnt really much time left to discuss every possible option as all changes need to be locked in by friday...

**Comment by aylinfi** [comment]
grafik

New colour mockup for the deer and shallow water, that Glennn and I did.
Deer: #2ecddc, Shallow: #a3f9ff

**Review by mango-gremlin — APPROVED** [review]
(imma approve so we can merge once we're done)

Everything else was already said by aylin, we tested out the colours in the level and I think they're different enough now to not look weird.

**Comment by marcel-iv** [comment]
> New colour mockup for the deer and shallow water, that Glennn and I did. Deer: #2ecddc, Shallow: #a3f9ff

Implemented that, I'll keep the PR open briefly, if someone wants any last-minute changes

**Pull request merged**
