### PR TITLE
bridges | bridge inventory but local first

### LINKED ISSUE #172: bridges | Implement basic animal Inventory
## Motivation
Way to track which animals you have in your party/and can use for bridges.

## Implementation
The implementation should provide a basic inventory:

This inventory should be like the inventory already implemented in the overworld.

It should have the following functionality
- saves how many of each animal you have (should be expandable to work with the singleton in the future -> so that it can take the inventory content information from the player in the future)
  The amounts of each animal should/could be saved in a dictionary where key = AnimalType (as represented in the singleton) and value = how many you have 
  It would be great if each value, before it is saved into the dict, is exported with @export to that you can edit the animal amounts in the godot inspector.
- save how many animals have been used so far
- display and disable placement if animal not available
- the inventory should only take info out of the singleton, *not edit it* unless the level is completed and the player goes back to the overworld.

There should be a basic UI as follows:
- hbox container that contains buttons for each animal type & shows how many you have of each type
- the buttons should spawn the respective animal
- spawning animal should update inventory

### PR DESCRIPTION
**Pull request by ScatteredDrifter**
## Motivation
this resolves #172 like #241 does but **with a local implementation**

## What was changed/added

We load the singleton animal-inventory once and then use it locally until a function to **leave the scene** is called to "set the update animal inventory to _global state_".

I've taken @Raining-Cloud methods to implement the inventory and adapted them to comply with the _local only_ aspect. 

## Testing

You should be able to run it locally an start the "grid" scene. 
~~There you will have an inventory of 1,1,0,1 which could also be changed with the method `set_animal_inventory()` within "Grid". **This acts as placeholder for the Singleton Inventory** because it defaults to an empty inventory making it harder to test.~~ 
You can set the inventory by manually setting an inventory in the Singleton --> animal_inventory

~~**IMPORTANT**: Before merging this initialization should be updated to load from the **singleton** instead! 
Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.~~
done in efbbbff

### CODE REVIEW

**Comment by ScatteredDrifter** [comment]
merged main to get rid of the conflicts.

**Review by aylinfi — APPROVED** [review]
Inventory seems to work, code looks good too. 
Are the FIXMEs supposed to stay for now?

**Comment by ScatteredDrifter** [comment]
> Inventory seems to work, code looks good too. Are the FIXMEs supposed to stay for now?

most are not, I've removed them and further unused statements / expressions from this implementation. 
Could you have another look @aylinfi ?

**Review by aylinfi — APPROVED** [review]
lg but all the animals in the inventory are set to 0 now?

**Comment by ScatteredDrifter** [comment]
> lg but all the animals in the inventory are set to 0 now?

@aylinfi 
Well yes because on default the player does not have any inventory. 
As seen in the singleton_player you can set the player-inventory with a debug-inventory to have  non 0 values.

**Pull request merged**
