### PR TITLE
changed the TileSet Image to the Frog

### LINKED ISSUE #249: bridges | frog hazard
## Motivation
For some levels, we want to have frogs as hazards.

## Implementation
Under res://assets/art/tilesets/bridge_tileset/ there's the hazard tileset image (bridge_bramble_tiles.png). Edit the image and add the frog sprite, you should find it on the ui-assets channel on Discord or some older versions of this project.
Everything else should work automatically.

### PR DESCRIPTION
**Pull request by trashsolid123**
## Motivation
closes #249

Changed the Image of the Frog Tile 
the png of the Frog is now 10 x 10 Pixel.

## Testing

https://github.com/mango-gremlin/arch-enemies/assets/44133213/6f39bbca-7132-4202-835f-90e29394c1ac

### CODE REVIEW

**Review by mango-gremlin — CHANGES_REQUESTED** [review]
Unless I am missing something, I think you misread the issue. The task was not to replace the existing sprites.
The task was to add the frog as an alternative to the existing hazard sprites. A hazard should be a frog OR the original hazards. You just deleted the hazards. This was not the idea.

**Comment by trashsolid123** [comment]
Yes, I misread. Now the Frog can be used with the existing sprites.

image

**Review by Kabooni — CHANGES_REQUESTED** [review]
Everything is fine, but I have one stupid request. I'm sorry. Could you move the frog one pixel down in bridge_bramble_tiles.png? It would prevent the frog from hovering above the ground.

**Review by mango-gremlin — APPROVED** [review]
nice, thanks!
Once the frog is moved down a pixel and @Kabooni has approved as well, you can merge this

**Comment by trashsolid123** [comment]
image
the Frog is now 1 pixel lower but still hovering because of the other Texture.

**Review by Kabooni — APPROVED** [review]
Thanks!

**Pull request merged**
