### PR TITLE
about page | added names, links to fonts and github and licensing information

### LINKED ISSUE #374: add content to about page in-game
## Things to add
- our names
- github link
- credits: godot license, art, sounds

### PR DESCRIPTION
**Pull request by mango-gremlin**
## Motivation
closes #374 

About page should contain some information on the contributors and credits.

## What was changed/added
removed the colons in the headings here as per @marcel-iv 's request
image

image

### CODE REVIEW

**Review by marcel-iv — APPROVED** [review]
Looks very good!

The only thing we could change is to add sound to the LinkButtons, and remove the invisible frog in the about scene. But neither is important, we can just merge it now

**Comment by mango-gremlin** [comment]
> Looks very good!
> 
> The only thing we could change is to add sound to the LinkButtons, and remove the invisible frog in the about scene. But neither is important, we can just merge it now

I added sound to the link buttons but there is no sound when i press them :( could be just because of my PC, or because it opens a link in another program idk? maybe you can test it, could be that im doing something wrong

**Comment by ScatteredDrifter** [comment]
Agreed looks good and provides the necessary information ^

**Comment by marcel-iv** [comment]
> I added sound to the link buttons but there is no sound when i press them :( could be just because of my PC, or because it opens a link in another program idk? maybe you can test it, could be that im doing something wrong

Everything works as expected on my machine, and the signals seem to be connected just fine

**Pull request merged**
