### PR TITLE
bridges | update the turorials

### LINKED ISSUE #357: bridges | fix multiple things in tutorial
## Motivation

- margins in tutorial boxes
- explain all buttons in tutorial
- explain fox mode in tutorial
- notification that you can get more animals (if unsolved quests remain)
- make spider tutorial in level 1 AND 2 depend on if spider acquired

## Implementation

### PR DESCRIPTION
**Pull request by aylinfi**
## Motivation
closes #357

After playtesting we realized more things needed to be explained in the tutorial.

## What was changed/added
Tutorial slides for "What is the goal?", "What are the different zone colours?", "What do the buttons do?" and "What are the spiky things and why do frogs kill me?" have been added.
All pictures have been updated to enclude the new zone colours and a slight margin has been added to the text, which is also centered now.

The spider turorial now appears before both level 1 and 2 and also reminds the player to talk to the npc to get more animal allies.

## Testing

https://github.com/mango-gremlin/arch-enemies/assets/116217918/10a0a376-0d4e-4e92-817f-95c23e79e2d7

### CODE REVIEW

**Review by Kabooni — APPROVED** [review]
Everythings works, thank you!
The deer tutorial has the typo again, but I'm not sure if this branch includes the typo fixes, so it could be fine.
grafik
The squirrel tutorial has some typos
grafik
Honestly I would rewrite this a bit, the second sentence is a bit long

**Review by mango-gremlin — APPROVED** [review]
looks great and works, thanks!

Where you explain the buttons:
Maybe also refer to the questionmark and where to find it?
Technically it would be also nice if you had a little picture next to the explanation maybe with arrows pointing to the buttons? if that is not too compilicated - the text is a bit much and i dont think anyone will remember all that without visuals :(

**Comment by aylinfi** [comment]
grafik

Buttons tutorial now looks like this

**Comment by Kabooni** [comment]
The new button tutorial is great, thanks! I would merge it now then

**Pull request merged**
