### PR TITLE
Constructed final bridge levels and overworld

### LINKED ISSUE #257: overworld | assets indicating an item interaction & items
## Motivation
If we remove the dummy asset that is used to show an item-interaction it **won't be noticeable at all**, hence we do require some sort of **sprite to indicate** an item.

This should **not be too obvious**, yet also giving a **hint**that something might be found there. 

ADDITIONALLY: Sprites for the items from game design docs should be added.

## Implementation
1. add the new sprite, replace the **dummy-sprite** from the **item_interaction.tscn**
2. test whether its fine placed near a tree / bush

### LINKED ISSUE #258: overworld | design / implement final overworld
## Motivation
implement the actual overworld ( i.e tilemap)  in our **overworld-scene**  

## Implementation

do it within the `main_scene_overworld`

### LINKED ISSUE #281: bridges | design / implement bridge levels
## Motivation
The game needs to have playable levels.

## Implementation
Instantiate 3 new bridge scenes, connect using singleton (bridge edges), Implement levels as seen in wiki.

### PR DESCRIPTION
**Pull request by mango-gremlin**
**WHEN TESTING: DELETE YOUR OLD SAVE FILE (SEE WIKI) OR THE FOX WILL LAND IN THE WATER**

## Motivation
closes #281 
closes #258
closes #257 

The final game as shown in Wiki/Story had to be implemented.

I apologize for the gigantic PR :(

### Bridges
- added the three levels: 0_Tutorial, 1_FrogHazard, 2_Final
- changed fox jump height because for some reason, fox did not jump over 3 blocks -> i thought we had said 3 blocks so a fox can clear a deer with a jump, which might be necessary when you dont have many animals to build stairs with. If this should be changed, say so, but we then need to add more animals, and it might be a bit annoying for players if they cant just jump over.
- changed fox hitbox so platforming with hazards is more satisfying -> the hitbox doesnt extend past the fox anymore, so you only die when you think you should
- pause menu location adjusted -> now always in the middle
- aspect ratio adjusted so levels do not look squished

**unfinished:**
**problems/bugs: bramble in level 1 overlaps with new inventory (doesnt really matter actually)**

### Overworld
- added the final overworld with four islands, one main one and three smaller ones (as seen in Story)
- added items drawn by @Kabooni ; added function that automatically assigns item sprite to the right item & updated items in backend to be the new items
- added all npcs that were planned, as well as functionality for the quests, which items to bring them etc
- added all bridges and connected them via bridge edges
- added the theme to the dialogue box -> UI needs to be further adjusted
- UI for inventory updated: shows sprites of animals and items next to amount you have
- UI for dialogue boxes now fits with the theme, increased font size
- last level solved -> u can now cross the bridge; @ScatteredDrifter noticed I forgot to add the tiles with no collision
- Inventory now updates and deducts animals used during solved levels

**unfinished:**
**problems/bugs: -**

**will be done in separate issues:**
- Starting Cutscene pictures  #300 
- Dialogue text, include npc portraits #303 

**probably no time (if someone has time, feel free to do this): final bridge interaction appears only when quest done**

## Testing
I'll include some screenshots when I've eaten lunch lol

## Additional Information
if anything else was forgotten, needs to be added, pls say so. First take a look in the 'unfinished' section

### CODE REVIEW

**Comment by Kabooni** [comment]
#290 should be merged before, as it provides some adjustments for this branch.

**Comment by Raffael-Rack** [comment]
The upper left bramble hazard in the frog level is currently overlapped by the Inventory Interface, maybe it should be moved slightly to the right and down.

**Comment by marcel-iv** [comment]
Looks *very* good, the levels seem to be exactly like we wanted, and the quest seem to work from what I've seen. I've initially struggled to even play the game, for some reason my player spawned in the water, and couldn't get back on the islands, if someone else runs into that problem, just edit the save file (-> wiki). 

However, I found one issue that persisted, at least on my end. When playing Level 1 or 2, the aspect ratio was a bit off, everything was stretched, at least I think so? Level 0 seems fine. I don't know if thats solely a problem on my end, so it would be nice if someone could verify that. 
Level 1

Also, after finishing the final level, I couldn't walk on the bridge, and restarting the game resets all bridges. I'm not sure which of those are tracked, or even intended, but I thought it useful to mention them here.

**Comment by mango-gremlin** [comment]
> The upper left bramble hazard in the frog level is currently overlapped by the Inventory Interface, maybe it should be moved slightly to the right and down.

@aylinfi maybe you could adjust the brambles? sorry for placing them there in the first place x.x



> Looks _very_ good, the levels seem to be exactly like we wanted, and the quest seem to work from what I've seen. I've initially struggled to even play the game, for some reason my player spawned in the water, and couldn't get back on the islands, if someone else runs into that problem, just edit the save file (-> wiki).

-> yeah fair point, I could have said you need to do this.. the old island location was somewhere else because I changed the shape of the island. I will edit the pr with a warning to delete save files first.

> However, I found one issue that persisted, at least on my end. When playing Level 1 or 2, the aspect ratio was a bit off, everything was stretched, at least I think so? Level 0 seems fine. I don't know if thats solely a problem on my end, so it would be nice if someone could verify that.

I did notice that as well, and initially thought it was the camera zoom but I had already adjusted that. If anyone has an idea what happened, feel free to change it. I will look into it tomorrow.
Interestingly enough though, earlier in the week, on my linux laptop, the aspect ratio had no problems; maybe its OS specific OR the aspect ratio got fucked along the way somewhere. maybe @aylinfi could investigate this as well since it is the bridge levels.
 
> Also, after finishing the final level, I couldn't walk on the bridge, and restarting the game resets all bridges. I'm not sure which of those are tracked, or even intended, but I thought it useful to mention them here.

OH that is not good, i tested it with the other two levels and thought the last one was fine lol, sorry. I will check the connections tomorrow. The game should reset all bridges upon restarting, as they are not tracked at the moment (@ScatteredDrifter might change that, but its not a must) - but the bridge def should be built when finishing the level. I had a similar problem with the frog hazard level earlier because aylin changed the names of the files, so I will check tomorrow if that is the case, that's an easy fix.
(@aylinfi maybe tell me in future when you change file names, as the file paths to levels are hard coded)

**Comment by marcel-iv** [comment]
Just to clarify, when finishing the final level, the bridge is built, but I'm seemingly unable to actually walk over it, see video below. I'm guessing this is some sort of hitbox issue, all horizontal bridges work just fine. 

https://github.com/mango-gremlin/arch-enemies/assets/104799849/c4c53b11-fd7e-4120-9c41-67063e330e35

**Comment by mango-gremlin** [comment]
> Just to clarify, when finishing the final level, the bridge is built, but I'm seemingly unable to actually walk over it, see video below. I'm guessing this is some sort of hitbox issue, all horizontal bridges work just fine.

yes, that is what i expected you meant. i ran into the same issue earlier. The bridge is built when you solve the level, but the hitbox that usually prevents you from walking into the water (the island edge has no collision at bridge points) only gets removed once the singleton confirms this level fits this bridge edge. Last time, this didnt work because the file path i specified for the bridge edge was the wrong path. If there is a different issue, it might have to do with the different template for the vertical bridge
I will check really quick whether it's just the file name, one sec

**Comment by Kabooni** [comment]
>I did notice that as well, and initially thought it was the camera zoom (because the other levels are longer) but I had already adjusted that. If anyone has an idea what happened, feel free to change it. I will look into it tomorrow.
Interestingly enough though, earlier in the week, on my linux laptop, the aspect ratio had no problems; maybe its OS specific OR the aspect ratio got fucked along the way somewhere. maybe @aylinfi could investigate this as well since it is the bridge levels.

The cameras are still zoomed in uneven, e.g. like this in the frog level
grafik

**Comment by mango-gremlin** [comment]
> > I did notice that as well, and initially thought it was the camera zoom (because the other levels are longer) but I had already adjusted that. If anyone has an idea what happened, feel free to change it. I will look into it tomorrow.
> > Interestingly enough though, earlier in the week, on my linux laptop, the aspect ratio had no problems; maybe its OS specific OR the aspect ratio got fucked along the way somewhere. maybe @aylinfi could investigate this as well since it is the bridge levels.
> 
> The cameras are still zoomed in unevenly, e.g. like this in the frog level 

OH okay fair, I misunderstood. I will test this later, thank you!!

**Review by marcel-iv — APPROVED** [review]
Everything seems we wanted to work seems to work, and everything else will be tracked in separate issues

**Pull request merged**
