### PR TITLE
Bridges: Walking sound continues after reaching goal area

### LINKED ISSUE #323: Bridges: Walking sound keeps playing after reaching the goal
## Description
Bridges: Walking sound keeps playing after reaching the goal

**To Reproduce**
Reach the goal, continue to press d

### PR DESCRIPTION
**Pull request by DerSimi**
## Motivation
closes #323 

## Testing
Code is "solid", tested it locally.

### CODE REVIEW

**Review by Kabooni — APPROVED** [review]
Lgtm, but "tested it locally" is basically useless for us as proof of if it's working. You should include a video or something, it would make the reviewer's life a lot easier.

**Comment by ScatteredDrifter** [comment]
> Lgtm, but "tested it locally" is basically useless for us as proof of if it's working. You should include a video or something, it would make the reviewer's life a lot easier.

hm partially. 
After all a video is not a proof that its working for everyone either ^^ 
Giving instructions on how to replicate ( if it was bug or so ) or what to try in order to validate testing would make more sense . (( or having CI :eyes: )) 

Its somewhat necessary to have everyone pull and run the tests locally too ^

**Comment by DerSimi** [comment]
> Giving instructions on how to replicate ( if it was bug or so ) or what to try in order to validate testing would make more sense . (( or having CI 👀 ))

See the linked issue

What to try is obvious: Do it on the main branch and to it on this branch :)

**Comment by ScatteredDrifter** [comment]
> See the linked issue 

But most of the time ppl might prefer having it presented once more because it reduces the amount of work / effort to take ^

**Pull request merged**
