### PR TITLE
Refactor Player into Singleton | improve Interaction system | set framework for NPC Interaction | update Bridge-representation

### LINKED ISSUE #134: overworld | bridges |  represent player as singleton to have globally available states
## Motivation

In any situation we require information about the player. I.e: 

in **bridge building**:
- which and how many animals are available
- which items are useable 
- which animals were used / lost during construction of the bridge ( and should not be in inventory after leaving this game ) 

in **overworld**:
- where are we currently
- do we meet requirements to interact with certain item ? 
- what ought to be shown in the hud? 
- ...

Currently those information are _stored_ in the **player.gd** that is solely used for the overworld.
Furthermore its state is saved whenever **changing a scene** which makes the whole game rather inefficient.

## Implementation

We would like to resolve this by **instantiating a global state** that every scene should be capable of querying / writing data  from / to. 

For that we could possibly use **singletons** [more here](https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html)

### PR DESCRIPTION
**Pull request by ScatteredDrifter**
Its been long, its been late, I'm sorry. 

This PR primarily wants to resolve #134 --> the conversion from the whole player and its state into a globally accessible _singleton_ structure. 
This restructure allows different scenes to access the current state of the player ( inventory / animals in inventory and similar ) or to query information from it. 

Furthermore it **centralizes** saving and loading a world-state into this single position.
resolves: #137  as every bridge is now denoted by its starting and destination node ( being an edge so to say ). We save the progress and state of the graph in an adjacency list within the player singleton. 
Upon interaction with a bridge its status is checked and thus it will notify us whether we have solved it or not. 

resolves: #180  
-> **although this needs refinement**, I will link further information in a new issue soon 
sets adaptable framework for representation of a bridge level #91 
-> we use BridgeEdge structures that contain a starting and destination point ( denoting an island ) which are then stored in our player and also within each node itself. They  query their status upon initialization of the world 
More information here: https://github.com/mango-gremlin/arch-enemies/wiki/04-Overworld-Navigation
 
resolves: #186 

**WITH THE ADDITION OF #206 being merged**
We are now resolving the following issues too: 
Resolves https://github.com/mango-gremlin/arch-enemies/issues/195 || Overworld | improve internal representation of items and animal inventory

Resolves https://github.com/mango-gremlin/arch-enemies/issues/190 || Overworld | add animal inventory to singleton_player

starts with https://github.com/mango-gremlin/arch-enemies/issues/189 || Overworld | update Overworld UI to accommodate active quests, animal inventory

resolves https://github.com/mango-gremlin/arch-enemies/issues/205 || adding separate "Animal" class containing interpretation for the animal Enum

## Changes : 

I will list a large block of changes that were made and added / implemented in this PR. 
I am aware that this is **too much for one PR** and makes it **difficult to review and check**. I apologize for this behavior and will try to reduce the amount of work done in a single PR for the next part. 

**I tried commenting** everything I've added / changed and hope that it makes the code readable and useable. 

## | Changes | 

**overworld**:
- created a new overworld scene where we can play and test changes `overworld_test_scene` 
	- helps not to collide with more up to date implementations of our game, yet provides an area to test scenarios and more

**Player**:
- disallowing Player to move when **in dialogue** 
- mostly refactored to singleton that loads and manages those information 
- **loading/storing saves not done yet**
- updating the **ui** was moved to `Player` and is not contained in the `add_to_inventory()` of the singleton_player anymore

**Bridges**: 
- added system to denote connections between island ( via bridges)
	- bridges are described as (startID,destID)  structures and encapsulated in class "BridgeEdge" --> for ease of usage 
- Bridge-Connections are stored in an adjaceny-list, which is symmetrical (by implementation, not design) because of undirected graph
- querying status for a given edge (bridge) requires an instance of **BridgeEdge**
- methods for **bridge_interaction** were added
	- `visualize_status()` checks **solved**-status and either shows / hides all parts contained in `$bridge_parts` (which is and ought to be a child of bridge_interactionspots!)
	- `set_passability()` checks **solved**-state and either lets player pass or block walking along bridge
- both methods described are run **upon instantiation**  of the object itsefl

**ISSUES with that**: 
The following is not an issue per se, however it makes creating new bridges a little tedious. Its another issue denoted here: #TODO 
- linking two bridge-parts to contain the same child parts 
	- **can be solved** by creating new node which contains those (( and links them accordingly))!
- implementing a bridge connection requires one to 
	- set two individual bridge-elements  ( and set their ids to be the same)
	- adding a child-node which contains the collision ( which also ought to be shaped!)
	- updating the amount of bridge-parts and positioning them correctly to connect the island 

**NPC**: 
- created new class denoting an NPC
- _static func init_animal_inventory():_ was added to **singletonPlayer** _might be moving once we have converted / adapted initializing the inventory correctly_

**UI**: 
- update requesting / getting information about UI 
- added ui for animal inventory 
- unused elements were removed 

---

## Testing
Most interactions are the same as before. 
**We ought to update and change** the way the UI is updated / fed so here the initial bug of the inventory not loading is back #100  --> However its tracked in a new issue and easy to resolve again. 

**Whenever** entering a dialogue now **you will be stuck** until you press "Q" which will release the **in_dialogue** state from the player.

There are some additional issues with the NPC Interaction:
The animal_inventory is not implemented yet and thus does not increase upon receiving a new animal from somewhere. 
**The UI** is not tracking any animals either --> because they have not been implemented accordingly yet. 

## | Whats to be done | 

To complete the implementation some changes are necessary: 

1. removing most code from `npc_interaction` to its own class `NPC` which then acts as interface for the interaction itself 
2.  creating a representation for Animals such that we can easily track the amount of them we have stored 
3. implementing the npc dialogue system which is intertwined with the player class and the npc class. 
4. maybe refactoring portions from `singleton_player` to a new fraction that **coordinates** overworld/bridgelevel state management

### CODE REVIEW

**Comment by ScatteredDrifter** [comment]
further resolves #186

**Comment by ScatteredDrifter** [comment]
> Most interactions are the same as before.
We ought to update and change the way the UI is updated / fed so here the initial bug of the inventory not loading is back https://github.com/mango-gremlin/arch-enemies/issues/100 --> However its tracked in a new issue and easy to resolve again.

This has been resolved with commit 0260f8e

**Comment by DerSimi** [comment]
I already worked on it while solving the dialogue issues and it does the job. There are some points I'm unsure of, e. g. the necessarity for NPC_interaction. 

Regarding the singleton configuration, this looks like a DerSimi Job. I will do it, as soon as the dialogue system is finished.

**Comment by ScatteredDrifter** [comment]
@DerSimi  could you elaborate on this comment? 
> Regarding the singleton configuration, this looks like a DerSimi Job. I will do it, as soon as the dialogue system is finished.

Do you mean the **4.** point of the "whats to be done" section?

**Comment by ScatteredDrifter** [comment]
While resolving the merge conflict - caused by the newly implemented tilemap - I added some basic npcs to interact with again, to allow showcasing the interaction and quests with them.

**Review by DerSimi — APPROVED** [review]

**Pull request merged**
